version: '3'

services:
  app:
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mongodb
      args:
      - mongodb_username=${MONGODB_USERNAME}
      - mongodb_password=${MONGODB_PASSWORD}
      - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - ./.data/mongo:/data/db:rw
    env_file:
      - .env
    ports:
      - "27017:27017"